name: tests

on:
  push:
    branches:
      - main
      - '*.x'
  pull_request:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-latest]
        php: [8.2, 8.3, 8.4, 8.5]
        ugarit: [11, 12, 13]
        exclude:
          - php: 8.5
            ugarit: 11
          - ugarit: '13'
            php: 8.2

    name: PHP ${{ matrix.php }} - Ugarit ${{ matrix.ugarit }} - ${{ matrix.os }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo, pdo, sqlite, pdo_sqlite
          ini-values: error_reporting=E_ALL
          tools: composer:v2.8
          coverage: none

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress --with='heritage/contracts:^${{ matrix.ugarit }}'

      - name: Execute tests
        run: vendor/bin/pest
